Define default value for FIELD_ENCRYPTION_KEY
Without a default value it fails with `AttributeError: 'Settings' object has no attribute 'FIELD_ENCRYPTION_KEY'`, so we need to provide `None` as default which is used in the next line to check if it's defined or not and raise an `ImproperlyConfigured` exception.